######################################################################
# Automatically generated by qmake (3.1) Fri May 17 23:03:12 2024
######################################################################

TEMPLATE = app
TARGET = Signal_Slot
INCLUDEPATH += .

QT += widgets

# Input
SOURCES += main.cpp
