######################################################################
# Automatically generated by qmake (3.1) Fri May 17 23:56:43 2024
######################################################################

TEMPLATE = app
TARGET = Subclassing
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += mydialog.h
SOURCES += main.cpp mydialog.cpp
