######################################################################
# Automatically generated by qmake (3.1) Fri May 17 17:14:25 2024
######################################################################

TEMPLATE = app
TARGET = Console
INCLUDEPATH += .

QT += widgets

# Input
SOURCES += main.cpp
